### ISSUE TITLE
Support specified floating-point precision

### ISSUE THREAD

**Issue by karlind** [haochengxia/vscode-numpy-viewer#10]
Float number(float32, float64, etc) shows with high precision, such as 0.14997714517421926. Hope to add an option to set the display precision of floating point numbers.

**Comment by haochengxia** [comment]
Thanks for your constructive issue! That's detailed. But I'd still like to get some advice on the default precision for floating point numbers. How about keeping 6 digits after the decimal point?

**Comment by karlind** [comment]
I think it's better to have no limit on precision by default. Adding an option to set the required precision can  keep consistent with numpy.

**Comment by haochengxia** [comment]
This feature is supported in v0.1.7 now ~

**Comment by karlind** [comment]
That's awosome!
