### ISSUE TITLE
Unable to open 'xxx.npy' Assertion Failed: argument is undefined or null

### ISSUE THREAD

**Issue by pluckpeng** [haochengxia/vscode-numpy-viewer#2]
Hello haochengxia, thanks for your work! But I got some problems when using the extension. When I open a .npy file, It warned me as the title showed. Could you help me to figure it out? 

![image](https://user-images.githubusercontent.com/58391900/179343831-5e78686d-6020-4a07-8e60-1c4f81f41d84.png)
![image](https://user-images.githubusercontent.com/58391900/179343834-d7f74850-baa1-4e17-ace3-9373ade7dd77.png)

**Comment by haochengxia** [comment]
Could you offer the .npy file which raises the error or give other approach to reproduce the problem?

**Comment by haochengxia** [comment]
All right, I've found this file on [a github repo](https://github.com/dizhenx/dizhen). This error causes by the lack of string array support. I add this feature in the recent updated version (v0.0.8). You can check the update now~

![image](https://user-images.githubusercontent.com/44400703/179351180-9eb58a0a-b749-4a03-ab23-5d2fd35a8ca3.png)

---
If you are interested in the implementation, each element of the string array in numpy is simply stored in a fixed size block of memory, and reading them in order is sufficient.
![image](https://user-images.githubusercontent.com/44400703/179350956-bfbddbbb-ab2a-43d7-b065-82e5b64c3144.png)

**Comment by haochengxia** [comment]
BTW, Thanks for your valuable issue. Any issues/PRs are welcome 😊.

**Comment by pluckpeng** [comment]
Thanks a lot! It really helps! Sorry for forgetting to leave the file and didn’t response in time. Hope your work goes better and better!
