### ISSUE TITLE
View 'dict' stored in npy

### ISSUE THREAD

**Issue by jasongzy** [haochengxia/vscode-numpy-viewer#4]
Thanks a lot for the nice work!

Is it possible to support for `npy` file that contains a **dict** object? That kind of `npy` is common in many machine learning projects. Currently, the extension just raises an error:

> Assertion Failed: argument is undefined or null

A simple snippet to produce such `npy` file:

```python
import numpy as np

data = {"data": np.random.rand(2, 2)}
np.save("data.npy", data)

print(np.load("data.npy", allow_pickle=True))
```

**Comment by haochengxia** [comment]
Thanks for your suggestion! But it seems a tricky feature for an extension written in TypeScript. The `.npy` file containing a **dict** object uses `pickle` module to serialize the python object and it makes trouble when we want to read it without a python (python 3.x) environment. 

And I have NOT found an appropriate module that can convert a python object to a TypeScript or JavaScript object (even readable string) although [kaitai-struct](http://kaitai.io/) offers a parser for the `python-pickle` protocol.

```
pickle.dump(np.array({'abcd' : 'abcd'}), fw, protocol=3)
00000000: 8003 636e 756d 7079 2e63 6f72 652e 6d75  ..cnumpy.core.mu
00000010: 6c74 6961 7272 6179 0a5f 7265 636f 6e73  ltiarray._recons
00000020: 7472 7563 740a 7100 636e 756d 7079 0a6e  truct.q.cnumpy.n
00000030: 6461 7272 6179 0a71 014b 0085 7102 4301  darray.q.K..q.C.
00000040: 6271 0387 7104 5271 0528 4b01 2963 6e75  bq..q.Rq.(K.)cnu
00000050: 6d70 790a 6474 7970 650a 7106 5802 0000  mpy.dtype.q.X...
00000060: 004f 3871 0789 8887 7108 5271 0928 4b03  .O8q....q.Rq.(K.
00000070: 5801 0000 007c 710a 4e4e 4e4a ffff ffff  X....|q.NNNJ....
00000080: 4aff ffff ff4b 3f74 710b 6289 5d71 0c7d  J....K?tq.b.]q.}
00000090: 710d 5804 0000 0061 6263 6471 0e68 0e73  q.X....abcdq.h.s
000000a0: 6174 710f 622e                           atq.b.

np.save('data.npy', np.array({'abcd' : 'abcd'}))
00000000: 934e 554d 5059 0100 7600 7b27 6465 7363  .NUMPY..v.{'desc
00000010: 7227 3a20 277c 4f27 2c20 2766 6f72 7472  r': '|O', 'fortr
00000020: 616e 5f6f 7264 6572 273a 2046 616c 7365  an_order': False
00000030: 2c20 2773 6861 7065 273a 2028 292c 207d  , 'shape': (), }
00000040: 2020 2020 2020 2020 2020 2020 2020 2020
00000050: 2020 2020 2020 2020 2020 2020 2020 2020
00000060: 2020 2020 2020 2020 2020 2020 2020 2020
00000070: 2020 2020 2020 2020 2020 2020 2020 200a                 .
00000080: 8003 636e 756d 7079 2e63 6f72 652e 6d75  ..cnumpy.core.mu
00000090: 6c74 6961 7272 6179 0a5f 7265 636f 6e73  ltiarray._recons
000000a0: 7472 7563 740a 7100 636e 756d 7079 0a6e  truct.q.cnumpy.n
000000b0: 6461 7272 6179 0a71 014b 0085 7102 4301  darray.q.K..q.C.
000000c0: 6271 0387 7104 5271 0528 4b01 2963 6e75  bq..q.Rq.(K.)cnu
000000d0: 6d70 790a 6474 7970 650a 7106 5802 0000  mpy.dtype.q.X...
000000e0: 004f 3871 0789 8887 7108 5271 0928 4b03  .O8q....q.Rq.(K.
000000f0: 5801 0000 007c 710a 4e4e 4e4a ffff ffff  X....|q.NNNJ....
00000100: 4aff ffff ff4b 3f74 710b 6289 5d71 0c7d  J....K?tq.b.]q.}
00000110: 710d 5804 0000 0061 6263 6471 0e68 0e73  q.X....abcdq.h.s
00000120: 6174 710f 622e                           atq.b.
```

I'd be appreciated it if you find any js/ts module which can convert a python object to a js/ts object or string and let me know.

**Comment by jasongzy** [comment]
Thanks for your reply!

I found [some js modules](https://github.com/search?l=JavaScript&q=pickle+python&type=Repositories) that can convert Python pickled objects to Javascript objects. I'm not an expert in js/ts, so I'm not sure if those modules are helpful.

However, I don't think there is a generic way to extract arbitrary `.npy` files without a Python environment. The **object array** stored in `.npy` can contain objects produced by any built-in/third-party module. If that specific module is missing, even native Python cannot read it properly.

In that case, I think maybe it's better to offer a workaround for this feature:

1. Write a simple Python script that tries to read a `.npy` file with `np.load(allow_pickle=True)` and outputs the content. It should catch any exception that occurs (e.g. broken npy file, module not installed). Something like:

```python
try:
    import numpy as np
    content = np.load(path, allow_pickle=True)
    print(content)
except Exception as e:
    print(e)
```

2. Introduce a setting item for a user-specified path of Python interpreter (by default the `python` from system env).

3. If the current js-numpy-parser fails to read a `.npy` file, execute the Python script with the user-specified interpreter.

4. Process the output of Python script with js/ts and show the content / raise an error.

Not very elegant 😂 but works

**Comment by haochengxia** [comment]
Yep! Indeed, I have considered a similar approach as I saw some extensions for python will invoke python code. However, it means a python interpreter is _mandatory_ and it is pretty different from the current implementation (If there are a python interpreter with `numpy`, we do not need to parse `.npy` files manually). Thus, I'd create a new repo for it. It is now in progress. Hopefully I can release it in next week~ 😺

**Comment by jasongzy** [comment]
Great! Looking forward to that~ I'll close this issue for now.

BTW, just a thought: with a Python interpreter, the extension can be developed into **vscode-pydata-viewer**. Not only `.npy`, but also `.pkl` (pickle) and even `.pth` (pytorch) 🤩
