### ISSUE TITLE
Add support for Numpy array with complex number

### ISSUE THREAD

**Issue by shubiuh** [haochengxia/vscode-numpy-viewer#8]
### Complex number

Hi, this is a useful tool for the Numpy array. However, the complex number is not supported yet. I would recommend adding support for complex numbers.

**Comment by haochengxia** [comment]
Thanks for your constructive issue! I didn't think about complex numbers when I implemented them because I didn't have a situation to use them. The support for `complex number` will be added into the next version which will be published in a week.

**Comment by haochengxia** [comment]
Complex number has been supported by #9
